Add SSR content
turbobeast/advanced-react-training-slides pull request #3
Opened 2017-04-26 19:37 UTC by rbrander

2017-04-26 19:54 UTC, turbobeast commented on src/content/introduction.md
> +- Install dependencies: `npm install`
I added `clone`, `cd` and `npm install` to slide `/#/3` "Get Started". Maybe just add `git checkout branch`

2017-04-26 19:54 UTC, turbobeast commented on src/content/introduction.md
> +- Install dependencies: `npm install`
Keep `npm install` if there are new deps you don't add while live-coding.

2017-04-27 13:52 UTC, rbrander commented
Updated the slide based on your feedback

2017-04-27 17:22 UTC, turbobeast requested changes
looks good, just needs two small changes.

2017-04-27 17:22 UTC, turbobeast commented on src/content/introduction.md
> +- Create a branch off master: `git checkout master -b add-ssr`
it should be `git checkout -b add-ssr`

2017-04-27 17:22 UTC, turbobeast commented on src/content/introduction.md
> +- initial DOM and state are generated and served
capitalize `Initial` for consistency

2017-04-27 18:31 UTC, rbrander commented on src/content/introduction.md
> +- Create a branch off master: `git checkout master -b add-ssr`
I intentionally did it this way to ensure they would be branching off from the starting point.  In the event they were already on a branch for the routing, using your command would actually branch off the current branch, and not master.

2017-04-27 18:36 UTC, turbobeast commented on src/content/introduction.md
> +- Create a branch off master: `git checkout master -b add-ssr`
okay, that makes sense

2017-04-27 18:37 UTC, turbobeast approved these changes
looks good :shipit:

2017-04-27 19:01 UTC, merged